name: miniweather
description: "MiniWeather is a personal project developed in Flutter that
  provides a simple and efficient interface for checking the current weather.
  The app also displays hourly forecasts and weather conditions for the next 3
  days, including minimum and maximum temperatures."
publish_to: "none"
version: 1.3.4+12

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  connectivity_plus: ^6.0.5
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  go_router: ^14.2.1
  intl: ^0.20.2
  loading_animation_widget: ^1.2.1
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.10

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/imgs/
    - .env

flutter_native_splash:
  color: "#2b4678"

flutter_intl:
  enabled: true
